Recipes/urls.py
from django.urls import path,re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'recipes'
urlpatterns = [
    path('create/',views.food_create,name='food_create'),
    re_path(r'^food/(?P<pk>\d+)/update/$',views.LocationUpdateView.as_view(),name='food_update'),
    re_path(r'^food/(?P<pk>\d+)/detail/$',views.food_detail,name='food_detail'),
    path('about_me/',views.about_me,name='about_me'),
    path('search/',views.search,name="search"),


]

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'basicapp'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

monk/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls')),
    path('recipes/',include('Recipes.urls')),
    path('',views.home,name='home'),
]
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Recipes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Food(models.Model):
    user=models.ForeignKey('auth.User',on_delete='CASCADE',related_name='foods',blank=True)
    food_name=models.CharField(max_length=25,blank=False)
    food_des=models.TextField(max_length=1000)
    food_in=models.CharField(max_length=25)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def get_absolute_url(self):
        return reverse('home')
    def __str__(self):
        return self.food_name

account/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User):

    def __str__(self):
        return "@{}".format(self.username)

Recipes/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Food




class FoodForm(forms.ModelForm):
    class Meta():
        model=Food
        fields = ('food_name','food_des','food_in','profile_pic')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['food_name'].label = 'Recipe Name'
        self.fields['food_des'].label = "Description"
        self.fields['food_in'].label = "Ingredients"
        self.fields['profile_pic'].label = "Upload Photo"


class FoodFormUpdate(forms.ModelForm):
    class Meta():
        model=Food
        fields = ('food_name','food_des','food_in')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['food_name'].label = 'Recipe Name'
        self.fields['food_des'].label = "Description"
        self.fields['food_in'].label = "Ingredients"

account/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields=('username','email','password1','password2','first_name')
        model=get_user_model()
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Confirm Password"
        self.fields['first_name'].label = "Your Name"

Recipes/views.py
from django.shortcuts import render

from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import View,UpdateView
from django.urls import reverse_lazy,reverse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms,models
from django.contrib.auth.mixins import LoginRequiredMixin
@login_required
def food_create(request):
    registered = False
    if request.method == "POST":
        user_form = forms.FoodForm(data=request.POST)
        if user_form.is_valid():
            use = user_form.save(commit=False)

            #use.save()
            use.user=request.user
            if 'profile_pic' in request.FILES:
                use.profile_pic = request.FILES['profile_pic']
            use.save()

            registered = True
            return redirect(reverse_lazy('home'))
        else:
            print(user_form.errors)
    else:

        user_form =forms.FoodForm()
    return render(request,'file_upload.html',{
                                    'user_form':user_form,
                                    'registered':registered,
    })
class LocationUpdateView(UpdateView,LoginRequiredMixin):
    model = models.Food
    template_name = 'food_update.html'
    form_class = forms.FoodFormUpdate
    success_url = reverse_lazy('home')


@login_required
def food_detail(request,pk):
    a=models.Food.objects.get(pk=pk)


    return render(request,'food_detail.html',{
                                    'a':a,
    })
def about_me(request):



    return render(request,'about_me.html',{})

@login_required
def search(request):
    if request.method=="POST":
        srch=request.POST['srh']
        if srch:
            match=models.Food.objects.filter(Q(food_name__icontains=srch)|
                                             Q(food_in__icontains=srch)
                                             )
            if match:
                
                return render(request,'search.html',{'data':match,})
            else:
                return render(request,'search.html',{'da':"Oops! Recipe Not Matched",})
        else:
            return HttpResponseRedirect(reverse('home'))

    return HttpResponseRedirect(reverse('home'))

account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('basicapp:login')
    template_name = 'accounts/signup.html'

monk/views.py
from django.shortcuts import render

from django.views.generic import TemplateView
from Recipes import models

def home(request):
    data = models.Food.objects.all()
    return render(request,'index.html',{'data':data,})

templates/about_me.html
{% extends 'index.html' %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block content %}


<div class="container">


  <div class="col" style="margin-left:320px;margin-top:10px;">
     <div class="card text-dark" style="width: 20rem;">
 <img src="{% static 'images/saurabh.jpg'%}" class="card-img-top" alt="..." height="300" width="70">
 <div class="card-body" style="text-align:center;">
   <h2 class="card-title" style="font-family:'Permanent Marker';" >SAURABH SINGH</h2>
   </div>
 <ul class="list-group list-group-flush" style="text-align:center;">
   <li class="list-group-item">INFORMATION TECHNOLOGY</li>
   <li class="list-group-item">IET LUCKNOW</li>
   <li class="list-group-item">PYTHON/DJANGO DEVELOPER</li>
   <li class="list-group-item"><a href="https://drive.google.com/open?id=1rxO_3Z4twJ2TBsMKb7cdvmUg0XKLAkSJ">CV</a></li>
   <li class="list-group-item"><a href="http://saurabh9767.pythonanywhere.com/" target="_blank"class="card-link">See my previous Project</a>
</li>
 </ul>
 <div class="card-body" style="text-align:center;">
   <a href="https://github.com/97saurabh" target="_blank" class="card-link">GITHUB</a>
   <a href="https://www.linkedin.com/in/saurabh-singh-ba5301158/" target="_blank"class="card-link">LinkedIn</a>
   </div>

</div>

   </div>
</div>




{% endblock %}

templates/accounts/login.html
{% extends 'index.html' %}
{% load bootstrap3 %}



{% block content %}


<div class="container">



  <h1 style="font-family:'Montserrat';text-align:center;">Log In</h1>

  <form method="POST">

    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class="btn btn-primary" value="LogIn" style="margin-left:500px;">
    
  </form>

</div>




{% endblock %}

templates/accounts/signup.html
{% extends 'index.html' %}
{% load bootstrap3 %}




{% block content %}



<div class="container">



  <h1 style="font-family:'Montserrat';text-align:center;">SignUp</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class="btn btn-primary" value="SignUp" style="margin-left:500px;">
  </form>

</div>




{% endblock %}

templates/file_upload.html
{% extends 'index.html' %}
{% load bootstrap3 %}



{% block content %}


<div class="container">



  <h1 style="font-family:'Montserrat';text-align:center;">Add Your Food  Recipe</h1>
  {% if registered %}
  <h1>Created</h1>
  {% else %}
  <form method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {% bootstrap_form user_form %}

    <input type="submit" class="btn btn-primary" value="Submit" style="margin-left:500px;">

  </form>
  {% endif %}

</div>




{% endblock %}

templates/food_detail.html
{% extends 'index.html' %}
{% load bootstrap3 %}



{% block content %}


<div class="container jumbotron">
  <div class="media">
  <img src="{{ a.profile_pic.url }}" class="mr-3" alt="NoT Available" height="350" width="350">
  <div class="media-body">
    <h4 class="mt-0" style="font-family:'Montserrat';">Recipe : {{ a.food_name }}</h4>
    <h5 style="font-family: 'Simonetta';">Ingredients Used : {{ a.food_in }}</h5>
    <p>Description : {{ a.food_des }}</p>

    {% if a.user == request.user %}
    <a class="btn btn-primary btn-lg" href="{% url 'recipes:food_update' pk=a.pk %}" role="button">Update</a>
    {% endif %}



  </div>
</div>



</div>




{% endblock %}

templates/food_update.html
{% extends 'index.html' %}
{% load bootstrap3 %}



{% block content %}


<div class="container">



  <h1 style="font-family:'Montserrat';text-align:center;">Update Your Recipe</h1>
  {% if registered %}
  <h1>Created</h1>
  {% else %}
  <form method="POST">

    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class="btn btn-primary" value="UPDATE" style="margin-left:500px;">

  </form>
  {% endif %}

</div>




{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Food</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Permanent+Marker|Simonetta&display=swap" rel="stylesheet">
  </head>
  <body style="background-color: #d9accf;">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">Food Recipes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'recipes:about_me' %}"> About Me <span class="sr-only">(current)</span></a>
          </li>
          </ul>
          <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <form class="form-inline my-2 my-lg-0" method="POST" action="/recipes/search/">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search Recipes" aria-label="Search" name="srh">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:food_create' %}">Create Recipes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="">Welcome {{ user.first_name }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:logout' %}">LogOut</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:login' %}">LogIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:signup' %}">Register</a>
          </li>
          {% endif %}
        </ul>

      </div>
    </nav>
    <div class="container jumbotron" style="margin-top:10px;">


    {% block content %}
    {% if user.is_authenticated %}
    {% for i in data %}
    {% if not forloop.counter|divisibleby:2 %}

      <div class="row" style="margin-left:120px;">

      {% endif %}

      <div class="cols card" style="margin-left:95px;" >

        <div class="card-body" style="width: 18rem;text-align: center;" >
          <h5 class="card-title" style="font-family:'Montserrat';" >{{ i.food_name|upper }}</h5>
          <p class="card-text" style=""font-family: 'Simonetta';"">Food Ingredients : {{ i.food_in|capfirst }}</p>
          <a href="{% url 'recipes:food_detail' pk=i.pk %}" class="btn btn-primary">Learn more</a>
          </div>
      </div>
      {% if forloop.counter|divisibleby:2 %}

    </div>
    <hr>
        {% endif %}
    {% endfor %}

    {% else %}
    <div class="jumbotron">

      <h2 style="font-family:'Simonetta';">Task</h2>
      <ul>
        <li>Create a simple web app that displays Food Recipes.</li>
        <li>Users should be able to login and search for food recipes based on name or the
        ingredients used.</li>
        <li>Once the user selects one of the recipes, transition to a new page where you will
        display images, description, ingredients and the steps related to the Recipe.</li>
        <li> Additonaly a user should be able to sign up, Login and add/edit his/her own
        recipes.</li>
      </ul>
      <h3 style="font-family:'Simonetta';">Solution</h3>
      <ul>
        <li> Visit This Site </li>
        <li> <a href="https://drive.google.com/file/d/1ntDMDvIwtCtgWMGMMdmt9pEfUMndbVAw/view">Watch This Video</a> </li>
        <li> <a href="https://github.com/97saurabh/Recipes">Private Repository</a> </li>


      </ul>

    </div>


    {% endif %}


    {% endblock %}
</div>

  </body>
</html>

templates/search.html
{% extends 'index.html' %}
{% load bootstrap3 %}



{% block content %}


<div class="container jumbotron">


  <h4 style="font-family:'Montserrat';text-align:center;">{{ da }}</h4>
  {% for i in data %}
  {% if not forloop.counter|divisibleby:2 %}

    <div class="row" style="margin-left:120px;">

    {% endif %}

    <div class="cols card" style="margin-left:95px;" >

      <div class="card-body" style="width: 18rem;text-align: center;" >
        <h5 class="card-title" style="font-family:'Montserrat';" >{{ i.food_name|upper }}</h5>
        <p class="card-text" style=""font-family: 'Simonetta';"">Food Increeients : {{ i.food_in|capfirst }}</p>
        <a href="{% url 'recipes:food_detail' pk=i.pk %}" class="btn btn-primary">Learn more</a>
        </div>
    </div>
    {% if forloop.counter|divisibleby:2 %}

  </div>
  <hr>
      {% endif %}
  {% endfor %}




</div>




{% endblock %}